.PHONY: schema

COMPOSE ?= docker compose
SCHEMA_COMPOSE_PROJECT := bouncer-schema
SCHEMA_PG_PORT ?= 5437
SCHEMA_DATABASE_URL ?= postgres://bouncer:bouncer@localhost:$(SCHEMA_PG_PORT)/bouncer?sslmode=disable
SCHEMA_OUT := server/db/schema.sql

schema:
	SCHEMA_PG_PORT=$(SCHEMA_PG_PORT) $(COMPOSE) -p $(SCHEMA_COMPOSE_PROJECT) -f compose.schema.yaml up -d --wait postgres
	status=0; \
	DATABASE_URL="$(SCHEMA_DATABASE_URL)" $(MAKE) migrate || status=$$?; \
	if [ $$status -eq 0 ]; then \
		{ \
			echo '-- Generated by `make schema`. Do not edit by hand.'; \
			echo '-- Source of truth is numbered files in server/db/migrations/.'; \
			echo; \
			SCHEMA_PG_PORT=$(SCHEMA_PG_PORT) $(COMPOSE) -p $(SCHEMA_COMPOSE_PROJECT) -f compose.schema.yaml exec -T postgres \
				pg_dump -U bouncer -d bouncer --schema-only --no-owner --no-privileges; \
		} > $(SCHEMA_OUT) || status=$$?; \
	fi; \
	SCHEMA_PG_PORT=$(SCHEMA_PG_PORT) $(COMPOSE) -p $(SCHEMA_COMPOSE_PROJECT) -f compose.schema.yaml down -v; \
	exit $$status

migrate:
	cd server && go run ./cmd/migrate
