/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Apps auth
 * Shared sign-in for a directory of static apps.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './mutator';
import type { ErrorType , BodyType } from './mutator';
export interface Error {
  message: string;
}

export interface LoginRequest {
  username: string;
  password: string;
  fingerprint?: string;
}

export interface RedeemRequest {
  code: string;
  nickname: string;
  fingerprint: string;
}

export type SessionKind = typeof SessionKind[keyof typeof SessionKind];


export const SessionKind = {
  user: 'user',
  temporary: 'temporary',
} as const;

export type SessionRole = typeof SessionRole[keyof typeof SessionRole];


export const SessionRole = {
  admin: 'admin',
  user: 'user',
} as const;

export interface Session {
  kind: SessionKind;
  username?: string;
  nickname?: string;
  role?: SessionRole;
  apps: string[];
  expiresAt: string;
  /** Public URL of the homepage. */
  hub: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  admin: 'admin',
  user: 'user',
} as const;

export interface User {
  id: string;
  username: string;
  role: UserRole;
  disabled: boolean;
  apps: string[];
}

export interface UserList {
  users: User[];
}

export interface CreateUserRequest {
  username: string;
  password: string;
}

export type UpdateUserRequestRole = typeof UpdateUserRequestRole[keyof typeof UpdateUserRequestRole];


export const UpdateUserRequestRole = {
  admin: 'admin',
  user: 'user',
} as const;

export interface UpdateUserRequest {
  password?: string;
  disabled?: boolean;
  role?: UpdateUserRequestRole;
}

export interface AppListRequest {
  slugs: string[];
}

export interface AccessCode {
  id: string;
  code: string;
  label: string;
  url: string;
  expiresAt: string;
  maxSignups: number;
  signupCount: number;
  /** @nullable */
  revokedAt?: string | null;
  apps: string[];
  createdAt: string;
}

export interface AccessCodeList {
  codes: AccessCode[];
}

export interface CreateAccessCodeRequest {
  label?: string;
  appSlugs: string[];
  expiresAt: string;
  maxSignups: number;
}

export interface TemporaryAccount {
  id: string;
  nickname: string;
  createdIp: string;
  lastIp: string;
  createdAt: string;
  /** @nullable */
  revokedAt?: string | null;
}

export interface TemporaryAccountList {
  accounts: TemporaryAccount[];
}

export interface DeployRequest {
  sha?: string;
  remote?: string;
}

export interface CloneRequest {
  remote: string;
  name: string;
  branch?: string;
}

export interface CloneApp {
  source: string;
}

export interface CloneResult {
  path: string;
  remote: string;
  branch: string;
  apps: CloneApp[];
}

export interface CreateAppRequest {
  slug: string;
  name: string;
  description: string;
  icon: string;
  source: string;
}

export type DeployRunStatus = typeof DeployRunStatus[keyof typeof DeployRunStatus];


export const DeployRunStatus = {
  running: 'running',
  published: 'published',
  failed: 'failed',
} as const;

export interface DeployRun {
  sha: string;
  status: DeployRunStatus;
  startedAt: string;
  /** @nullable */
  finishedAt?: string | null;
  log: string;
}

export interface DeployRepo {
  path: string;
  remote: string;
  branch: string;
  latest?: DeployRun | null;
}

export interface DeployStatus {
  enabled: boolean;
  remote: string;
  branch: string;
  webhookUrl: string;
  latest?: DeployRun | null;
  repos: DeployRepo[];
}

/**
 * Request failed.
 */
export type ErrorResponse = Error;

export type GitHookBody = { [key: string]: unknown };

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const login = (
    loginRequest: BodyType<LoginRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Session>(
      {url: `/api/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }




export const getLoginMutationKey = () => ['login'] as const;

export const getLoginMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext> => {

const mutationKey = getLoginMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, LoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginRequest>
    export type LoginMutationError = ErrorType<ErrorResponse>
    export type LoginMutationVariables = {data: BodyType<LoginRequest>}

    export const useLogin = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,LoginMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        LoginMutationVariables,
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }

export const logout = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/logout`, method: 'POST', signal
    },
      options);
    }




export const getLogoutMutationKey = () => ['logout'] as const;

export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = getLogoutMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {


          return  logout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>

    export type LogoutMutationError = ErrorType<unknown>


    export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options), queryClient);
    }

export const getSession = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Session>(
      {url: `/api/session`, method: 'GET', signal
    },
      options);
    }




export const getGetSessionQueryKey = () => {
    return [
    `/api/session`
    ] as const;
    }


export const getGetSessionQueryOptions = <TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({ signal }) => getSession(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getSession>>>
export type GetSessionQueryError = ErrorType<ErrorResponse>


export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorType<ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSession>>,
          TError,
          Awaited<ReturnType<typeof getSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSession<TData = Awaited<ReturnType<typeof getSession>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const redeemAccessCode = (
    redeemRequest: BodyType<RedeemRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Session>(
      {url: `/api/access-codes/redeem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: redeemRequest, signal
    },
      options);
    }




export const getRedeemAccessCodeMutationKey = () => ['redeemAccessCode'] as const;

export const getRedeemAccessCodeMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof redeemAccessCode>>, TError,RedeemAccessCodeMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof redeemAccessCode>>, TError,RedeemAccessCodeMutationVariables, TContext> => {

const mutationKey = getRedeemAccessCodeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof redeemAccessCode>>, RedeemAccessCodeMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  redeemAccessCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RedeemAccessCodeMutationResult = NonNullable<Awaited<ReturnType<typeof redeemAccessCode>>>
    export type RedeemAccessCodeMutationBody = BodyType<RedeemRequest>
    export type RedeemAccessCodeMutationError = ErrorType<ErrorResponse>
    export type RedeemAccessCodeMutationVariables = {data: BodyType<RedeemRequest>}

    export const useRedeemAccessCode = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof redeemAccessCode>>, TError,RedeemAccessCodeMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof redeemAccessCode>>,
        TError,
        RedeemAccessCodeMutationVariables,
        TContext
      > => {
      return useMutation(getRedeemAccessCodeMutationOptions(options), queryClient);
    }

export const listUsers = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<UserList>(
      {url: `/api/users`, method: 'GET', signal
    },
      options);
    }




export const getListUsersQueryKey = () => {
    return [
    `/api/users`
    ] as const;
    }


export const getListUsersQueryOptions = <TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listUsers>>> = ({ signal }) => listUsers(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>
export type ListUsersQueryError = ErrorType<ErrorResponse>


export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsers>>,
          TError,
          Awaited<ReturnType<typeof listUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListUsers<TData = Awaited<ReturnType<typeof listUsers>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const createUser = (
    createUserRequest: BodyType<CreateUserRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<User>(
      {url: `/api/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserRequest, signal
    },
      options);
    }




export const getCreateUserMutationKey = () => ['createUser'] as const;

export const getCreateUserMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,CreateUserMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,CreateUserMutationVariables, TContext> => {

const mutationKey = getCreateUserMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, CreateUserMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = BodyType<CreateUserRequest>
    export type CreateUserMutationError = ErrorType<ErrorResponse>
    export type CreateUserMutationVariables = {data: BodyType<CreateUserRequest>}

    export const useCreateUser = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,CreateUserMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        CreateUserMutationVariables,
        TContext
      > => {
      return useMutation(getCreateUserMutationOptions(options), queryClient);
    }

export const updateUser = (
    id: string,
    updateUserRequest: BodyType<UpdateUserRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<User>(
      {url: `/api/users/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserRequest, signal
    },
      options);
    }




export const getUpdateUserMutationKey = () => ['updateUser'] as const;

export const getUpdateUserMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,UpdateUserMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,UpdateUserMutationVariables, TContext> => {

const mutationKey = getUpdateUserMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, UpdateUserMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  updateUser(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = BodyType<UpdateUserRequest>
    export type UpdateUserMutationError = ErrorType<ErrorResponse>
    export type UpdateUserMutationVariables = {id: string;data: BodyType<UpdateUserRequest>}

    export const useUpdateUser = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,UpdateUserMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        UpdateUserMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateUserMutationOptions(options), queryClient);
    }

export const setUserApps = (
    id: string,
    appListRequest: BodyType<AppListRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<User>(
      {url: `/api/users/${id}/apps`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: appListRequest, signal
    },
      options);
    }




export const getSetUserAppsMutationKey = () => ['setUserApps'] as const;

export const getSetUserAppsMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserApps>>, TError,SetUserAppsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof setUserApps>>, TError,SetUserAppsMutationVariables, TContext> => {

const mutationKey = getSetUserAppsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setUserApps>>, SetUserAppsMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  setUserApps(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetUserAppsMutationResult = NonNullable<Awaited<ReturnType<typeof setUserApps>>>
    export type SetUserAppsMutationBody = BodyType<AppListRequest>
    export type SetUserAppsMutationError = ErrorType<ErrorResponse>
    export type SetUserAppsMutationVariables = {id: string;data: BodyType<AppListRequest>}

    export const useSetUserApps = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserApps>>, TError,SetUserAppsMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setUserApps>>,
        TError,
        SetUserAppsMutationVariables,
        TContext
      > => {
      return useMutation(getSetUserAppsMutationOptions(options), queryClient);
    }

export const listAccessCodes = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AccessCodeList>(
      {url: `/api/access-codes`, method: 'GET', signal
    },
      options);
    }




export const getListAccessCodesQueryKey = () => {
    return [
    `/api/access-codes`
    ] as const;
    }


export const getListAccessCodesQueryOptions = <TData = Awaited<ReturnType<typeof listAccessCodes>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessCodes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAccessCodesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAccessCodes>>> = ({ signal }) => listAccessCodes(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAccessCodes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAccessCodesQueryResult = NonNullable<Awaited<ReturnType<typeof listAccessCodes>>>
export type ListAccessCodesQueryError = ErrorType<ErrorResponse>


export function useListAccessCodes<TData = Awaited<ReturnType<typeof listAccessCodes>>, TError = ErrorType<ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessCodes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAccessCodes>>,
          TError,
          Awaited<ReturnType<typeof listAccessCodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAccessCodes<TData = Awaited<ReturnType<typeof listAccessCodes>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessCodes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAccessCodes>>,
          TError,
          Awaited<ReturnType<typeof listAccessCodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAccessCodes<TData = Awaited<ReturnType<typeof listAccessCodes>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessCodes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListAccessCodes<TData = Awaited<ReturnType<typeof listAccessCodes>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessCodes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAccessCodesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const createAccessCode = (
    createAccessCodeRequest: BodyType<CreateAccessCodeRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AccessCode>(
      {url: `/api/access-codes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccessCodeRequest, signal
    },
      options);
    }




export const getCreateAccessCodeMutationKey = () => ['createAccessCode'] as const;

export const getCreateAccessCodeMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAccessCode>>, TError,CreateAccessCodeMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAccessCode>>, TError,CreateAccessCodeMutationVariables, TContext> => {

const mutationKey = getCreateAccessCodeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAccessCode>>, CreateAccessCodeMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createAccessCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAccessCodeMutationResult = NonNullable<Awaited<ReturnType<typeof createAccessCode>>>
    export type CreateAccessCodeMutationBody = BodyType<CreateAccessCodeRequest>
    export type CreateAccessCodeMutationError = ErrorType<ErrorResponse>
    export type CreateAccessCodeMutationVariables = {data: BodyType<CreateAccessCodeRequest>}

    export const useCreateAccessCode = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAccessCode>>, TError,CreateAccessCodeMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAccessCode>>,
        TError,
        CreateAccessCodeMutationVariables,
        TContext
      > => {
      return useMutation(getCreateAccessCodeMutationOptions(options), queryClient);
    }

export const revokeAccessCode = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<AccessCode>(
      {url: `/api/access-codes/${id}/revoke`, method: 'POST', signal
    },
      options);
    }




export const getRevokeAccessCodeMutationKey = () => ['revokeAccessCode'] as const;

export const getRevokeAccessCodeMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeAccessCode>>, TError,RevokeAccessCodeMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeAccessCode>>, TError,RevokeAccessCodeMutationVariables, TContext> => {

const mutationKey = getRevokeAccessCodeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeAccessCode>>, RevokeAccessCodeMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  revokeAccessCode(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeAccessCodeMutationResult = NonNullable<Awaited<ReturnType<typeof revokeAccessCode>>>

    export type RevokeAccessCodeMutationError = ErrorType<ErrorResponse>
    export type RevokeAccessCodeMutationVariables = {id: string}

    export const useRevokeAccessCode = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeAccessCode>>, TError,RevokeAccessCodeMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeAccessCode>>,
        TError,
        RevokeAccessCodeMutationVariables,
        TContext
      > => {
      return useMutation(getRevokeAccessCodeMutationOptions(options), queryClient);
    }

export const getAccessCodeQR = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<Blob>(
      {url: `/api/access-codes/${id}/qr`, method: 'GET',
        responseType: 'blob', signal
    },
      options);
    }




export const getGetAccessCodeQRQueryKey = (id: string,) => {
    return [
    `/api/access-codes/${id}/qr`
    ] as const;
    }


export const getGetAccessCodeQRQueryOptions = <TData = Awaited<ReturnType<typeof getAccessCodeQR>>, TError = ErrorType<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessCodeQR>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccessCodeQRQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccessCodeQR>>> = ({ signal }) => getAccessCodeQR(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAccessCodeQR>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAccessCodeQRQueryResult = NonNullable<Awaited<ReturnType<typeof getAccessCodeQR>>>
export type GetAccessCodeQRQueryError = ErrorType<ErrorResponse>


export function useGetAccessCodeQR<TData = Awaited<ReturnType<typeof getAccessCodeQR>>, TError = ErrorType<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessCodeQR>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessCodeQR>>,
          TError,
          Awaited<ReturnType<typeof getAccessCodeQR>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccessCodeQR<TData = Awaited<ReturnType<typeof getAccessCodeQR>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessCodeQR>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessCodeQR>>,
          TError,
          Awaited<ReturnType<typeof getAccessCodeQR>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccessCodeQR<TData = Awaited<ReturnType<typeof getAccessCodeQR>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessCodeQR>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAccessCodeQR<TData = Awaited<ReturnType<typeof getAccessCodeQR>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessCodeQR>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAccessCodeQRQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const listTemporaryAccounts = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<TemporaryAccountList>(
      {url: `/api/access-codes/${id}/accounts`, method: 'GET', signal
    },
      options);
    }




export const getListTemporaryAccountsQueryKey = (id: string,) => {
    return [
    `/api/access-codes/${id}/accounts`
    ] as const;
    }


export const getListTemporaryAccountsQueryOptions = <TData = Awaited<ReturnType<typeof listTemporaryAccounts>>, TError = ErrorType<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemporaryAccounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTemporaryAccountsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTemporaryAccounts>>> = ({ signal }) => listTemporaryAccounts(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTemporaryAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTemporaryAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof listTemporaryAccounts>>>
export type ListTemporaryAccountsQueryError = ErrorType<ErrorResponse>


export function useListTemporaryAccounts<TData = Awaited<ReturnType<typeof listTemporaryAccounts>>, TError = ErrorType<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemporaryAccounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTemporaryAccounts>>,
          TError,
          Awaited<ReturnType<typeof listTemporaryAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTemporaryAccounts<TData = Awaited<ReturnType<typeof listTemporaryAccounts>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemporaryAccounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTemporaryAccounts>>,
          TError,
          Awaited<ReturnType<typeof listTemporaryAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTemporaryAccounts<TData = Awaited<ReturnType<typeof listTemporaryAccounts>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemporaryAccounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListTemporaryAccounts<TData = Awaited<ReturnType<typeof listTemporaryAccounts>>, TError = ErrorType<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTemporaryAccounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTemporaryAccountsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const revokeTemporaryAccount = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/temporary-accounts/${id}/revoke`, method: 'POST', signal
    },
      options);
    }




export const getRevokeTemporaryAccountMutationKey = () => ['revokeTemporaryAccount'] as const;

export const getRevokeTemporaryAccountMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeTemporaryAccount>>, TError,RevokeTemporaryAccountMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeTemporaryAccount>>, TError,RevokeTemporaryAccountMutationVariables, TContext> => {

const mutationKey = getRevokeTemporaryAccountMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeTemporaryAccount>>, RevokeTemporaryAccountMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  revokeTemporaryAccount(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeTemporaryAccountMutationResult = NonNullable<Awaited<ReturnType<typeof revokeTemporaryAccount>>>

    export type RevokeTemporaryAccountMutationError = ErrorType<ErrorResponse>
    export type RevokeTemporaryAccountMutationVariables = {id: string}

    export const useRevokeTemporaryAccount = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeTemporaryAccount>>, TError,RevokeTemporaryAccountMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeTemporaryAccount>>,
        TError,
        RevokeTemporaryAccountMutationVariables,
        TContext
      > => {
      return useMutation(getRevokeTemporaryAccountMutationOptions(options), queryClient);
    }

export const gitHook = (
    gitHookBody: BodyType<GitHookBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/hooks/git`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: gitHookBody, signal
    },
      options);
    }




export const getGitHookMutationKey = () => ['gitHook'] as const;

export const getGitHookMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gitHook>>, TError,GitHookMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof gitHook>>, TError,GitHookMutationVariables, TContext> => {

const mutationKey = getGitHookMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof gitHook>>, GitHookMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  gitHook(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GitHookMutationResult = NonNullable<Awaited<ReturnType<typeof gitHook>>>
    export type GitHookMutationBody = BodyType<GitHookBody>
    export type GitHookMutationError = ErrorType<ErrorResponse>
    export type GitHookMutationVariables = {data: BodyType<GitHookBody>}

    export const useGitHook = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gitHook>>, TError,GitHookMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof gitHook>>,
        TError,
        GitHookMutationVariables,
        TContext
      > => {
      return useMutation(getGitHookMutationOptions(options), queryClient);
    }

export const getDeploy = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<DeployStatus>(
      {url: `/api/deploy`, method: 'GET', signal
    },
      options);
    }




export const getGetDeployQueryKey = () => {
    return [
    `/api/deploy`
    ] as const;
    }


export const getGetDeployQueryOptions = <TData = Awaited<ReturnType<typeof getDeploy>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeploy>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeployQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeploy>>> = ({ signal }) => getDeploy(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeploy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDeployQueryResult = NonNullable<Awaited<ReturnType<typeof getDeploy>>>
export type GetDeployQueryError = ErrorType<ErrorResponse>


export function useGetDeploy<TData = Awaited<ReturnType<typeof getDeploy>>, TError = ErrorType<ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeploy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeploy>>,
          TError,
          Awaited<ReturnType<typeof getDeploy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeploy<TData = Awaited<ReturnType<typeof getDeploy>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeploy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeploy>>,
          TError,
          Awaited<ReturnType<typeof getDeploy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeploy<TData = Awaited<ReturnType<typeof getDeploy>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeploy>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDeploy<TData = Awaited<ReturnType<typeof getDeploy>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeploy>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDeployQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const triggerDeploy = (
    deployRequest?: BodyType<DeployRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/deploy`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployRequest, signal
    },
      options);
    }




export const getTriggerDeployMutationKey = () => ['triggerDeploy'] as const;

export const getTriggerDeployMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerDeploy>>, TError,TriggerDeployMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerDeploy>>, TError,TriggerDeployMutationVariables, TContext> => {

const mutationKey = getTriggerDeployMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerDeploy>>, TriggerDeployMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  triggerDeploy(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerDeployMutationResult = NonNullable<Awaited<ReturnType<typeof triggerDeploy>>>
    export type TriggerDeployMutationBody = BodyType<DeployRequest> | undefined
    export type TriggerDeployMutationError = ErrorType<ErrorResponse>
    export type TriggerDeployMutationVariables = {data?: BodyType<DeployRequest>}

    export const useTriggerDeploy = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerDeploy>>, TError,TriggerDeployMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof triggerDeploy>>,
        TError,
        TriggerDeployMutationVariables,
        TContext
      > => {
      return useMutation(getTriggerDeployMutationOptions(options), queryClient);
    }

export const runDeploy = (
    deployRequest?: BodyType<DeployRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/deploy/run`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deployRequest, signal
    },
      options);
    }




export const getRunDeployMutationKey = () => ['runDeploy'] as const;

export const getRunDeployMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runDeploy>>, TError,RunDeployMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof runDeploy>>, TError,RunDeployMutationVariables, TContext> => {

const mutationKey = getRunDeployMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runDeploy>>, RunDeployMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  runDeploy(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RunDeployMutationResult = NonNullable<Awaited<ReturnType<typeof runDeploy>>>
    export type RunDeployMutationBody = BodyType<DeployRequest> | undefined
    export type RunDeployMutationError = ErrorType<ErrorResponse>
    export type RunDeployMutationVariables = {data?: BodyType<DeployRequest>}

    export const useRunDeploy = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runDeploy>>, TError,RunDeployMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runDeploy>>,
        TError,
        RunDeployMutationVariables,
        TContext
      > => {
      return useMutation(getRunDeployMutationOptions(options), queryClient);
    }

export const cloneRepo = (
    cloneRequest: BodyType<CloneRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<CloneResult>(
      {url: `/api/deploy/clones`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cloneRequest, signal
    },
      options);
    }




export const getCloneRepoMutationKey = () => ['cloneRepo'] as const;

export const getCloneRepoMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cloneRepo>>, TError,CloneRepoMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof cloneRepo>>, TError,CloneRepoMutationVariables, TContext> => {

const mutationKey = getCloneRepoMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cloneRepo>>, CloneRepoMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  cloneRepo(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CloneRepoMutationResult = NonNullable<Awaited<ReturnType<typeof cloneRepo>>>
    export type CloneRepoMutationBody = BodyType<CloneRequest>
    export type CloneRepoMutationError = ErrorType<ErrorResponse>
    export type CloneRepoMutationVariables = {data: BodyType<CloneRequest>}

    export const useCloneRepo = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cloneRepo>>, TError,CloneRepoMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cloneRepo>>,
        TError,
        CloneRepoMutationVariables,
        TContext
      > => {
      return useMutation(getCloneRepoMutationOptions(options), queryClient);
    }

export const createApp = (
    createAppRequest: BodyType<CreateAppRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/apps`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAppRequest, signal
    },
      options);
    }




export const getCreateAppMutationKey = () => ['createApp'] as const;

export const getCreateAppMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApp>>, TError,CreateAppMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createApp>>, TError,CreateAppMutationVariables, TContext> => {

const mutationKey = getCreateAppMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApp>>, CreateAppMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createApp(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateAppMutationResult = NonNullable<Awaited<ReturnType<typeof createApp>>>
    export type CreateAppMutationBody = BodyType<CreateAppRequest>
    export type CreateAppMutationError = ErrorType<ErrorResponse>
    export type CreateAppMutationVariables = {data: BodyType<CreateAppRequest>}

    export const useCreateApp = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApp>>, TError,CreateAppMutationVariables, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApp>>,
        TError,
        CreateAppMutationVariables,
        TContext
      > => {
      return useMutation(getCreateAppMutationOptions(options), queryClient);
    }

export const accessStream = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<string>(
      {url: `/api/access/stream`, method: 'GET', signal
    },
      options);
    }




export const getAccessStreamQueryKey = () => {
    return [
    `/api/access/stream`
    ] as const;
    }


export const getAccessStreamQueryOptions = <TData = Awaited<ReturnType<typeof accessStream>>, TError = ErrorType<ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accessStream>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAccessStreamQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof accessStream>>> = ({ signal }) => accessStream(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof accessStream>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AccessStreamQueryResult = NonNullable<Awaited<ReturnType<typeof accessStream>>>
export type AccessStreamQueryError = ErrorType<ErrorResponse>


export function useAccessStream<TData = Awaited<ReturnType<typeof accessStream>>, TError = ErrorType<ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof accessStream>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accessStream>>,
          TError,
          Awaited<ReturnType<typeof accessStream>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccessStream<TData = Awaited<ReturnType<typeof accessStream>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accessStream>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accessStream>>,
          TError,
          Awaited<ReturnType<typeof accessStream>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAccessStream<TData = Awaited<ReturnType<typeof accessStream>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accessStream>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAccessStream<TData = Awaited<ReturnType<typeof accessStream>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof accessStream>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAccessStreamQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
