-- Generated by `make schema`. Do not edit by hand.
-- Source of truth is numbered files in server/db/migrations/.

--
-- PostgreSQL database dump
--

\restrict lP5b2o0dQbRnjFCUcIuol1tEKKVAiVIWM7fRklfUAmSWeaQcpbQOc7LF3mw0ZiH

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access_code_apps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_code_apps (
    code_id uuid NOT NULL,
    slug text NOT NULL
);


--
-- Name: access_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_codes (
    id uuid NOT NULL,
    code text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    max_signups integer NOT NULL,
    revoked_at timestamp with time zone,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT access_codes_max_signups_check CHECK ((max_signups > 0))
);


--
-- Name: auth_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_attempts (
    bucket text NOT NULL,
    failures integer NOT NULL,
    locked_until timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: deploys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deploys (
    id uuid NOT NULL,
    sha text NOT NULL,
    status text NOT NULL,
    log text DEFAULT ''::text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    remote text DEFAULT ''::text NOT NULL,
    CONSTRAINT deploys_status_check CHECK ((status = ANY (ARRAY['running'::text, 'published'::text, 'failed'::text])))
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sessions (
    id uuid NOT NULL,
    token_hash text NOT NULL,
    user_id uuid,
    temporary_account_id uuid,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sessions_check CHECK ((((user_id IS NOT NULL) AND (temporary_account_id IS NULL)) OR ((user_id IS NULL) AND (temporary_account_id IS NOT NULL))))
);


--
-- Name: temporary_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.temporary_accounts (
    id uuid NOT NULL,
    access_code_id uuid NOT NULL,
    nickname text NOT NULL,
    fingerprint_hash text NOT NULL,
    created_ip text NOT NULL,
    last_ip text NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_apps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_apps (
    user_id uuid NOT NULL,
    slug text NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    username text NOT NULL,
    username_key text NOT NULL,
    password_hash text NOT NULL,
    role text DEFAULT 'user'::text NOT NULL,
    disabled boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'user'::text])))
);


--
-- Name: access_code_apps access_code_apps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_code_apps
    ADD CONSTRAINT access_code_apps_pkey PRIMARY KEY (code_id, slug);


--
-- Name: access_codes access_codes_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_codes
    ADD CONSTRAINT access_codes_code_key UNIQUE (code);


--
-- Name: access_codes access_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_codes
    ADD CONSTRAINT access_codes_pkey PRIMARY KEY (id);


--
-- Name: auth_attempts auth_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_attempts
    ADD CONSTRAINT auth_attempts_pkey PRIMARY KEY (bucket);


--
-- Name: deploys deploys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deploys
    ADD CONSTRAINT deploys_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_token_hash_key UNIQUE (token_hash);


--
-- Name: temporary_accounts temporary_accounts_access_code_id_fingerprint_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_accounts
    ADD CONSTRAINT temporary_accounts_access_code_id_fingerprint_hash_key UNIQUE (access_code_id, fingerprint_hash);


--
-- Name: temporary_accounts temporary_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_accounts
    ADD CONSTRAINT temporary_accounts_pkey PRIMARY KEY (id);


--
-- Name: user_apps user_apps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_apps
    ADD CONSTRAINT user_apps_pkey PRIMARY KEY (user_id, slug);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key_key UNIQUE (username_key);


--
-- Name: deploys_remote_started_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX deploys_remote_started_at ON public.deploys USING btree (remote, started_at DESC);


--
-- Name: deploys_started_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX deploys_started_at ON public.deploys USING btree (started_at DESC);


--
-- Name: access_code_apps access_code_apps_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_code_apps
    ADD CONSTRAINT access_code_apps_code_id_fkey FOREIGN KEY (code_id) REFERENCES public.access_codes(id) ON DELETE CASCADE;


--
-- Name: access_codes access_codes_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_codes
    ADD CONSTRAINT access_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: sessions sessions_temporary_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_temporary_account_id_fkey FOREIGN KEY (temporary_account_id) REFERENCES public.temporary_accounts(id) ON DELETE CASCADE;


--
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: temporary_accounts temporary_accounts_access_code_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.temporary_accounts
    ADD CONSTRAINT temporary_accounts_access_code_id_fkey FOREIGN KEY (access_code_id) REFERENCES public.access_codes(id) ON DELETE CASCADE;


--
-- Name: user_apps user_apps_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_apps
    ADD CONSTRAINT user_apps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict lP5b2o0dQbRnjFCUcIuol1tEKKVAiVIWM7fRklfUAmSWeaQcpbQOc7LF3mw0ZiH

